#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp   # bsp, float, stack
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                0
yabai -m config window_gap                   0

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="Evernote" manage=off
yabai -m rule --add app="Todoist" manage=off
yabai -m rule --add app="Microsoft Teams" manage=off


# personal spaces
# yabai -m config --space 3 layout float  # third monitor doesnt work with bsp

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus first"
# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus first" 



echo "yabai configuration loaded.."
