# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = '$username'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
format='[$path]($style)[$read_only]($read_only_style)'
truncation_length=1

[package]
disabled = true

[aws]
disabled=true

[git_branch]
format = '\[[$branch(:$remote_branch)]($style)\]'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style)'

[docker_context]
disabled=true

[nodejs]
disabled=true

[time]
time_format = "%T"
format = "$time($style)"
style = "bright-white"
disabled = false

[line_break]
disabled = false

